[package]
name = "monad"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/syntax"]
resolver = "3"

[workspace.dependencies]
miette = "7.6.0"
internment = "0.8.6"
thiserror = "2.0.17"

[dependencies]
syntax = { path = "crates/syntax" }
